"""add colum update_at in  users table

Revision ID: e59fec4fc70c
Revises: b96dafa7f8b1
Create Date: 2024-07-24 00:48:26.513596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59fec4fc70c'
down_revision: Union[str, None] = 'b96dafa7f8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
